spring:
  application:
    name: ssdcve

  datasource:
    url: jdbc:postgresql://localhost:5432/ssdcve
    username: ssdcve
    password: ssdcve_dev_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true


server:
  port: 6969
