/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/holder/credentials/{id}/disclosure": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getDisclosure"];
        put: operations["setDisclosure"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/verifier/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["verify"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/verifier/verify/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["verifyBatch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/verifier/verify/batch/csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["exportCsv"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/issuer/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/issuer/keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createKey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/issuer/credentials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list"];
        put?: never;
        post: operations["issue"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/issuer/credentials/{id}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["revoke"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/issuer/credentials/{id}/document": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["attachDocument"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/holder/wallet/{credentialId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["add"];
        delete: operations["remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["register_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{id}/promote-issuer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["promoteIssuer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/issuers/{id}/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["verifyIssuer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/verifier/verify/{credentialId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["verifyById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/verifier/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["history"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/verifier/chain/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["chainStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/verifier/anchors/recent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["recentAnchors"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/verifier/anchor/{credentialNumber}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["anchor"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/issuer/verifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["verifications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/issuer/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/issuer/holders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["holder"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/issuer/credentials/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/holder/wallet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["wallet"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/holder/credentials/{id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["download"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/holder/credentials/{id}/certificate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["certificate"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/verifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["verifications_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["users"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/issuers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["issuers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        DisclosureUpdateRequest: {
            hiddenClaims: string[];
        };
        DisclosureResponse: {
            claims?: {
                [key: string]: unknown;
            };
            hiddenClaims?: string[];
        };
        DisclosureInfo: {
            /** Format: int32 */
            disclosed?: number;
            /** Format: int32 */
            total?: number;
            complete?: boolean;
        };
        VerificationResult: {
            valid?: boolean;
            /** @enum {string} */
            status?: "VALID" | "TAMPERED" | "REVOKED" | "EXPIRED" | "NOT_FOUND" | "UNAVAILABLE";
            credentialNumber?: string;
            reason?: string;
            /** Format: uuid */
            issuerId?: string;
            issuerName?: string;
            issuerDomain?: string;
            issuerVerified?: boolean;
            claims?: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            issuedAt?: string;
            /** Format: date-time */
            expiresAt?: string;
            /** Format: date-time */
            verifiedAt?: string;
            anchorTxHash?: string;
            /** Format: int64 */
            anchorBlockNumber?: number;
            /** Format: int64 */
            anchorChainId?: number;
            anchorVerified?: boolean;
            disclosure?: components["schemas"]["DisclosureInfo"];
        };
        BatchItemResult: {
            fileName?: string;
            credentialNumber?: string;
            recipientName?: string;
            issuerName?: string;
            status?: string;
            valid?: boolean;
            checks?: components["schemas"]["VerificationChecks"];
            verificationResult?: components["schemas"]["VerificationResult"];
            errorMessage?: string;
        };
        BatchVerificationResponse: {
            batchId?: string;
            /** Format: int32 */
            total?: number;
            /** Format: int32 */
            processed?: number;
            /** Format: int32 */
            valid?: number;
            /** Format: int32 */
            tampered?: number;
            /** Format: int32 */
            revoked?: number;
            /** Format: int32 */
            expired?: number;
            /** Format: int32 */
            notFound?: number;
            /** Format: int32 */
            unavailable?: number;
            /** Format: int32 */
            failed?: number;
            /** Format: int64 */
            durationMs?: number;
            results?: components["schemas"]["BatchItemResult"][];
        };
        VerificationChecks: {
            envelopeStructure?: boolean;
            schemaConformance?: boolean;
            issuerSignature?: boolean;
            onChainAnchor?: boolean;
            revocationStatus?: boolean;
            ipfsIntegrity?: boolean;
        };
        IssuerRegisterRequest: {
            name: string;
            domain: string;
        };
        IssuerResponse: {
            /** Format: uuid */
            id?: string;
            name?: string;
            domain?: string;
            verified?: boolean;
            /** Format: date-time */
            createdAt?: string;
        };
        IssuerKeyResponse: {
            keyId?: string;
            publicKey?: string;
            algorithm?: string;
            active?: boolean;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            revokedAt?: string;
        };
        CredentialIssueRequest: {
            /** Format: uuid */
            subjectId: string;
            type: string;
            title: string;
            claims: {
                [key: string]: unknown;
            };
        };
        CredentialResponse: {
            /** Format: uuid */
            id?: string;
            credentialNumber?: string;
            type?: string;
            title?: string;
            /** Format: uuid */
            subjectId?: string;
            subjectName?: string;
            contentHash?: string;
            ipfsCid?: string;
            documentCid?: string;
            anchorTxHash?: string;
            /** Format: int64 */
            anchorBlockNumber?: number;
            /** Format: int64 */
            anchorChainId?: number;
            signature?: string;
            signatureAlgorithm?: string;
            keyId?: string;
            /** Format: date-time */
            issuedAt?: string;
            /** Format: date-time */
            expiresAt?: string;
            /** @enum {string} */
            status?: "ACTIVE" | "REVOKED";
        };
        RevokeRequest: {
            reason?: string;
        };
        RevokeResponse: {
            /** Format: uuid */
            credentialId?: string;
            credentialNumber?: string;
            /** @enum {string} */
            status?: "ACTIVE" | "REVOKED";
            /** Format: date-time */
            revokedAt?: string;
            reason?: string;
        };
        WalletCredentialResponse: {
            /** Format: uuid */
            credentialId?: string;
            credentialNumber?: string;
            type?: string;
            title?: string;
            /** Format: uuid */
            issuerId?: string;
            issuerName?: string;
            issuerDomain?: string;
            anchorTxHash?: string;
            /** Format: int64 */
            anchorBlockNumber?: number;
            /** Format: int64 */
            anchorChainId?: number;
            /** Format: date-time */
            issuedAt?: string;
            /** Format: date-time */
            expiresAt?: string;
            /** @enum {string} */
            status?: "ACTIVE" | "REVOKED";
        };
        RegisterRequest: {
            /** Format: email */
            email: string;
            password: string;
            fullName: string;
        };
        UserResponse: {
            /** Format: uuid */
            id?: string;
            email?: string;
            fullName?: string;
            /** @enum {string} */
            role?: "ISSUER" | "HOLDER" | "VERIFIER" | "ADMIN";
        };
        AuthResponse: {
            accessToken?: string;
            tokenType?: string;
            /** Format: int64 */
            expiresInSeconds?: number;
            /** Format: uuid */
            userId?: string;
            email?: string;
            fullName?: string;
            /** @enum {string} */
            role?: "ISSUER" | "HOLDER" | "VERIFIER" | "ADMIN";
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        AdminIssuerResponse: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            userId?: string;
            name?: string;
            domain?: string;
            verified?: boolean;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        VerificationHistoryResponse: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            credentialId?: string;
            credentialNumber?: string;
            /** @enum {string} */
            result?: "VALID" | "TAMPERED" | "REVOKED" | "EXPIRED" | "NOT_FOUND" | "UNAVAILABLE";
            reason?: string;
            /** Format: date-time */
            verifiedAt?: string;
        };
        ChainStatusResponse: {
            /** Format: int64 */
            chainId?: number;
            /** Format: int64 */
            latestBlock?: number;
            /** Format: int64 */
            anchoredCount?: number;
        };
        RecentAnchorResponse: {
            credentialNumber?: string;
            issuerName?: string;
            /** Format: int64 */
            blockNumber?: number;
            /** Format: date-time */
            anchoredAt?: string;
        };
        AnchorLookupResponse: {
            credentialNumber?: string;
            contentHash?: string;
            txHash?: string;
            /** Format: int64 */
            blockNumber?: number;
            /** Format: int64 */
            chainId?: number;
            anchorVerified?: boolean;
        };
        VerificationRecordResponse: {
            credentialNumber?: string;
            /** @enum {string} */
            status?: "ACTIVE" | "REVOKED";
            reason?: string;
            /** Format: date-time */
            revokedAt?: string;
            /** Format: date-time */
            issuedAt?: string;
            /** Format: date-time */
            expiresAt?: string;
        };
        AdminVerificationResponse: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            credentialId?: string;
            credentialNumber?: string;
            /** Format: uuid */
            verifierId?: string;
            /** @enum {string} */
            result?: "VALID" | "TAMPERED" | "REVOKED" | "EXPIRED" | "NOT_FOUND" | "UNAVAILABLE";
            reason?: string;
            /** Format: date-time */
            verifiedAt?: string;
        };
        AdminUserResponse: {
            /** Format: uuid */
            id?: string;
            email?: string;
            fullName?: string;
            /** @enum {string} */
            role?: "ISSUER" | "HOLDER" | "VERIFIER" | "ADMIN";
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getDisclosure: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DisclosureResponse"];
                };
            };
        };
    };
    setDisclosure: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DisclosureUpdateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DisclosureResponse"];
                };
            };
        };
    };
    verify: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    credentialFile: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerificationResult"];
                };
            };
        };
    };
    verifyBatch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    files?: string[];
                    /** Format: binary */
                    file?: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchVerificationResponse"];
                };
            };
        };
    };
    exportCsv: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchVerificationResponse"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": string;
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IssuerRegisterRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["IssuerResponse"];
                };
            };
        };
    };
    createKey: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["IssuerKeyResponse"];
                };
            };
        };
    };
    list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CredentialResponse"][];
                };
            };
        };
    };
    issue: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CredentialIssueRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CredentialResponse"];
                };
            };
        };
    };
    revoke: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RevokeRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RevokeResponse"];
                };
            };
        };
    };
    attachDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    document: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CredentialResponse"];
                };
            };
        };
    };
    add: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                credentialId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["WalletCredentialResponse"];
                };
            };
        };
    };
    remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                credentialId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    register_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                refresh_token?: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuthResponse"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                refresh_token?: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuthResponse"];
                };
            };
        };
    };
    promoteIssuer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    verifyIssuer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminIssuerResponse"];
                };
            };
        };
    };
    verifyById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                credentialId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerificationResult"];
                };
            };
        };
    };
    history: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerificationHistoryResponse"][];
                };
            };
        };
    };
    chainStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChainStatusResponse"];
                };
            };
        };
    };
    recentAnchors: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecentAnchorResponse"][];
                };
            };
        };
    };
    anchor: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                credentialNumber: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnchorLookupResponse"];
                };
            };
        };
    };
    verifications: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["VerificationRecordResponse"][];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["IssuerResponse"];
                };
            };
        };
    };
    holder: {
        parameters: {
            query: {
                email: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CredentialResponse"];
                };
            };
        };
    };
    wallet: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["WalletCredentialResponse"][];
                };
            };
        };
    };
    download: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
    certificate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
    verifications_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminVerificationResponse"][];
                };
            };
        };
    };
    users: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserResponse"][];
                };
            };
        };
    };
    issuers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminIssuerResponse"][];
                };
            };
        };
    };
}
